# yolobox — a Docker "blast-radius" devbox for agentic programming.
#
# Base: Ubuntu 26.04, non-root user mapped to the host uid:gid at build time
# (USERNAME defaults to the sanitised host username, see tools/box-user.sh).
# Everything is installed as root at BUILD time. At RUNTIME the launcher runs a
# PERSISTENT per-workdir container, unprivileged (--user, --cap-drop=ALL,
# no-new-privileges), with exactly ONE mount that masks the image: a Docker
# named volume, "yolobox-home", at /home.
#
# ┌───────────────────────────────────────────────────────────────────────────┐
# │ CRITICAL TRAP — the /home VOLUME masks anything baked under $HOME.          │
# │ Only /home is mounted over; /usr/local and /opt are plain image content, so │
# │ a rebuilt image always wins there. Therefore every tool BINARY must live on │
# │ a SYSTEM path (/usr/local/*, /usr/bin, /opt), never under $HOME. The ENV    │
# │ block below pins each installer's target to a system path so it holds at   │
# │ build AND run. Package caches (~/.npm, cargo registry, go/pkg/mod, ...) are │
# │ created idempotently by yolobox-init on every container create/start —     │
# │ never baked into the image — because an empty named volume is seeded from  │
# │ the image exactly ONCE, so a cache dir added to a future image would never │
# │ appear in an existing volume.                                              │
# └───────────────────────────────────────────────────────────────────────────┘
#
# The ONLY Docker named volume in this project is "yolobox-home", mounted at
# /home. /usr/local and /opt are NOT volumes — a named volume there would
# obscure every rebuilt image forever and nothing refreshes one. Instead the
# box is a persistent per-workdir container: /usr/local and /opt live in its
# writable layer, chowned to the box user (/usr/local only — /opt stays
# root-owned so the box user can't tamper with the rendered MCP configs it
# holds), so ad-hoc installs survive between `docker exec` sessions and a real
# rebuild still always wins.

FROM ubuntu:26.04

# ---------------------------------------------------------------------------
# Identity: create the box user with the host's uid:gid so files written to
# the /work bind-mount are owned by the host user. Passed by the launcher
# (via tools/build.sh) as build args. USERNAME is the sanitised host username
# (tools/box-user.sh), not the fixed literal `dev`.
# ---------------------------------------------------------------------------
ARG UID=1000
ARG GID=1000
ARG USERNAME=dev

# ---------------------------------------------------------------------------
# Genuinely global ENV: identity + locale. Static, and stays static -- unlike
# everything below it, no tools/*.sh module owns HOME/LANG/LC_ALL/
# DEBIAN_FRONTEND/YOLOBOX_USER.
# ---------------------------------------------------------------------------
# NOTE: HOME is pinned to /home/${USERNAME} so it SURVIVES the numeric `--user`
# the launcher passes at runtime (Docker would otherwise default HOME=/ for a
# numeric user).
ENV YOLOBOX_USER=${USERNAME}
ENV HOME=/home/${USERNAME} \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    DEBIAN_FRONTEND=noninteractive

# ---------------------------------------------------------------------------
# Per-tool install locations + PATH: generated by `tools/build.sh` from every
# tools/*.sh module's TOOL_ENV / TOOL_PATH -- see tools/README.md's runtime
# facet. Because they are ENV (not ARG) they persist into the running
# container, which is what makes the tools reachable once the /home volume
# masks $HOME.
#
# ONE `ENV` instruction per variable, deliberately: Docker `ENV` does NOT
# self-reference within a single instruction (a multi-pair `ENV
# FOO=${HOME}/x BAR=$FOO` would resolve `$FOO` to its value from BEFORE this
# instruction, not after -- see the Dockerfile reference on environment
# replacement) -- so a hand-collapsed multi-pair region would silently pin a
# home-relative variable below to the wrong value. `tools/install-all.sh`'s
# drift guard re-derives every value below from the live modules and fails
# the build, naming the offending variable, if this region and the modules
# disagree.
#
# DO NOT EDIT BY HAND. Regenerate with `tools/build.sh --regen-only` (or a
# full `tools/build.sh`) after changing any module's TOOL_ENV/TOOL_PATH.
# >>> generated from tools/*.sh by tools/build.sh — DO NOT EDIT BY HAND <<<
ENV NPM_CONFIG_PREFIX=/usr/local
ENV GOROOT=/usr/local/go
ENV GOPATH=/home/${USERNAME}/go
ENV CARGO_HOME=/usr/local/cargo
ENV RUSTUP_HOME=/usr/local/rustup
ENV BUN_INSTALL=/usr/local/bun
ENV UV_INSTALL_DIR=/usr/local/bin
ENV DISABLE_AUTOUPDATER=1
ENV CRUSH_GLOBAL_CONFIG=/opt/yolobox/mcp/crush.json
ENV OPENCODE_CONFIG=/opt/yolobox/mcp/opencode.json
ENV HERDR_INSTALL_DIR=/usr/local/bin
ENV FZF_DIR=/opt/fzf
ENV PLAYWRIGHT_BROWSERS_PATH=/var/lib/ms-playwright
ENV PATH=/usr/local/go/bin:/usr/local/cargo/bin:/usr/local/bun/bin:/opt/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
# >>> end generated <<<

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# ---------------------------------------------------------------------------
# 1) The toolchain: one module per tool under tools/, sourced and run by
#    install-all.sh (root, one collapsed layer — see tools/README.md for the
#    module contract). Replaces the old 13-RUN-layer, hand-copied-version
#    install matrix; adding or removing a tool is now a single-file change.
# ---------------------------------------------------------------------------
COPY tools/ /opt/yolobox/tools/
RUN chmod 0755 /opt/yolobox/tools/*.sh \
    && USERNAME_ARG="${USERNAME}" UID_ARG="${UID}" GID_ARG="${GID}" \
       /opt/yolobox/tools/install-all.sh

# ---------------------------------------------------------------------------
# 2) MCP library: one JSON fragment per server under mcp/, rendered at build
#    time into all four harness-native configs. Adding an MCP server is a
#    single-file change (drop a fragment in mcp/); every harness picks it up.
#    The rendered configs are root-owned and 0444/0555 so the (now writable,
#    /usr/local-owned) box user cannot rewrite which MCP servers exist —
#    /opt stays root-owned (tools/install-all.sh's cleanup only chowns
#    /usr/local), so a parent-directory rm/rename/mv can't defeat this either.
# ---------------------------------------------------------------------------
COPY mcp/ /opt/yolobox/mcp-src/
RUN chmod 0755 /opt/yolobox/mcp-src/*.sh \
    && /opt/yolobox/mcp-src/render.sh

# ---------------------------------------------------------------------------
# 3) Entrypoint + the per-exec init/shell handoff scripts (docker exec never
#    runs the image ENTRYPOINT, hence the split — see entrypoint.sh).
# ---------------------------------------------------------------------------
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
COPY yolobox-init /usr/local/bin/yolobox-init
COPY yolobox-shell /usr/local/bin/yolobox-shell
COPY herd-report.sh /opt/yolobox/herd-report.sh
RUN chmod 0755 /usr/local/bin/entrypoint.sh /usr/local/bin/yolobox-init \
        /usr/local/bin/yolobox-shell /opt/yolobox/herd-report.sh

# ---------------------------------------------------------------------------
# 4) Build-time smoke tests: resolve every tool from a SYSTEM path (proving
#    nothing critical was left under $HOME, which the /home volume would mask
#    at runtime), then speak MCP to every rendered server. Run as the real
#    user to catch permission traps.
# ---------------------------------------------------------------------------
USER ${USERNAME}
RUN /opt/yolobox/tools/smoke.sh
RUN /opt/yolobox/mcp-src/smoke.sh

# ---------------------------------------------------------------------------
# 5) Final trailer (MUST stay last): both smoke stages above write into $HOME
#    (`opencode --version` creates .cache/opencode etc; `go version` creates
#    .config/go/telemetry) — wipe it so the fresh /home volume seeds only the
#    empty, correctly-owned dir tools/02-user.sh created, never build residue.
#    Default back to the unprivileged user: a direct `docker run yolobox:local`
#    that bypasses the launcher then does NOT land as root. The launcher's
#    runtime --user still overrides this to the host uid:gid.
# ---------------------------------------------------------------------------
USER root
RUN USERNAME_ARG="${USERNAME}" UID_ARG="${UID}" GID_ARG="${GID}" \
        /opt/yolobox/tools/clean-home.sh
USER ${USERNAME}

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
