#!/usr/bin/env bash
# The toolchain phase runner. Runs as ROOT, once, at build time. Sources every
# tools/NN-name.sh module in LC_ALL=C filename order and drives it through the
# module contract documented in tools/lib.sh.
#
# Expects USERNAME_ARG, UID_ARG, GID_ARG in the environment (the Dockerfile's
# RUN step sets them).
set -euo pipefail

: "${USERNAME_ARG:?}" "${UID_ARG:?}" "${GID_ARG:?}"

here="/opt/yolobox/tools"
# shellcheck source=tools/lib.sh
source "${here}/lib.sh"

echo "=== phase 0a: drift guard (Dockerfile ENV region + runtime-env.generated) ==="
# Both generated artifacts only need module state plus the live env, both
# already available here -- so this runs BEFORE phase 3's tool_install
# (10-25 min of toolchain installs) rather than after, to fail fast instead
# of wasting the whole install on a stale generated file.
#
# The generated ENV region (Dockerfile) is already applied by the time this
# RUN executes, so $HOME/$GOROOT/$PATH/... below are the LIVE, baked values.
# Compare them against what the modules themselves declare: a hand-edited
# region, or a module change that never went through `tools/build.sh`, fails
# the build here, naming the offending variable.
#
# @HOME@ expands to the live $HOME (not a literal) here, unlike the region
# generator (which writes the literal ARG-expanding string) -- this is what
# makes the same TOOL_ENV declaration simultaneously host-independent (in the
# module) AND checkable in-image.
#
# No hashing tool: macOS ships shasum (SHA-1 default), ubuntu:26.04 ships
# sha256sum, and neither is guaranteed on both sides -- so this compares
# values directly instead.

ALL_DRIFT_PATH=()
ALL_DRIFT_RUNTIME_ENV=()
drift_cb() {
    local m="$1" entry key val expanded live
    if [ -n "${TOOL_ENV+x}" ]; then
        for entry in "${TOOL_ENV[@]}"; do
            key="${entry%%=*}"
            val="${entry#*=}"
            expanded="${val//@HOME@/$HOME}"
            live="${!key-}"
            if [ "${expanded}" != "${live}" ]; then
                echo "Dockerfile ENV region is stale — run tools/build.sh (${key}: image has '${live}', ${m} declares '${expanded}')" >&2
                exit 1
            fi
        done
    fi
    if [ -n "${TOOL_PATH+x}" ]; then
        ALL_DRIFT_PATH+=( "${TOOL_PATH[@]}" )
    fi
    if [ -n "${TOOL_RUNTIME_ENV+x}" ]; then
        ALL_DRIFT_RUNTIME_ENV+=( "${TOOL_RUNTIME_ENV[@]}" )
    fi
}
yb_each_module drift_cb

expected_path=""
for p in "${ALL_DRIFT_PATH[@]+"${ALL_DRIFT_PATH[@]}"}"; do
    expected_path="${expected_path}${p}:"
done
expected_path="${expected_path}${YB_FIXED_PATH_TAIL}"
if [ "${expected_path}" != "${PATH}" ]; then
    echo "Dockerfile ENV region is stale — run tools/build.sh (PATH: image has '${PATH}', expected '${expected_path}')" >&2
    exit 1
fi

# tools/runtime-env.generated ships into the image (COPY tools/) precisely so
# this check can run here: it is the mechanism that keeps it from drifting
# the same way the Dockerfile ENV region is kept from drifting above. @HOME@
# is left UNSUBSTITUTED (the launcher substitutes it at `docker exec` time),
# so this compares the file byte-for-byte against a re-derivation from the
# live modules, not against any expanded runtime value.
runtime_generated="${here}/runtime-env.generated"
expected_runtime_env="$(mktemp)"
{
    printf '# generated by tools/build.sh from tools/*.sh TOOL_RUNTIME_ENV -- DO NOT EDIT BY HAND\n'
    printf '# @HOME@ is substituted by the launcher (yolobox) at exec time, not here.\n'
    for entry in "${ALL_DRIFT_RUNTIME_ENV[@]+"${ALL_DRIFT_RUNTIME_ENV[@]}"}"; do
        printf '%s\n' "${entry}"
    done
} > "${expected_runtime_env}"
if ! cmp -s "${expected_runtime_env}" "${runtime_generated}"; then
    rm -f "${expected_runtime_env}"
    echo "tools/runtime-env.generated is stale — run tools/build.sh" >&2
    exit 1
fi
rm -f "${expected_runtime_env}"

echo "=== phase 0: bootstrap ==="
apt-get update
apt-get install -y --no-install-recommends ca-certificates gnupg curl

echo "=== phase 0b: gnupg homedir ==="
export GNUPGHOME=/tmp/gnupg
mkdir -p "${GNUPGHOME}"
chmod 700 "${GNUPGHOME}"

echo "=== phase 0c: tool_prepare ==="
phase0c_cb() {
    echo "--- phase0c ${TOOL_NAME:-${1}} ---"
    if declare -f tool_prepare >/dev/null 2>&1; then
        tool_prepare
    fi
}
yb_each_module phase0c_cb

echo "=== phase 1: tool_apt_repo ==="
phase1_cb() {
    echo "--- phase1 ${TOOL_NAME:-${1}} ---"
    if declare -f tool_apt_repo >/dev/null 2>&1; then
        tool_apt_repo
    fi
}
yb_each_module phase1_cb

echo "=== phase 2: apt batch ==="
ALL_APT=()
phase2_cb() {
    echo "--- phase2 ${TOOL_NAME:-${1}} ---"
    if [ -n "${TOOL_APT+x}" ]; then
        ALL_APT+=( "${TOOL_APT[@]}" )
    fi
}
yb_each_module phase2_cb
apt-get update
apt-get install -y --no-install-recommends "${ALL_APT[@]}"
locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8

echo "=== phase 3: tool_install ==="
phase3_cb() {
    echo "--- phase3 ${TOOL_NAME:-${1}} ---"
    if declare -f tool_install >/dev/null 2>&1; then
        tool_install
    fi
}
yb_each_module phase3_cb

echo "=== phase 3b: tool_configure ==="
# Build-time, root, per module -- runs after install, before the MCP render
# layer (a separate later RUN in the Dockerfile), which is what Claude's
# managed-settings.json and pi's herd-report extension both need
# (tool_configure must mkdir its own destination -- mcp/render.sh creates
# /etc/claude-code later, for the MCP file, not this one).
phase3b_cb() {
    echo "--- phase3b ${TOOL_NAME:-${1}} ---"
    if declare -f tool_configure >/dev/null 2>&1; then
        tool_configure
    fi
}
yb_each_module phase3b_cb

echo "=== phase 3c: manifests ==="
# Generated files the launch path reads INSTEAD of sourcing modules:
# yolobox-init reads these, never tools/lib.sh or tools/NN-*.sh.
mkdir -p /opt/yolobox/manifest

# home-dirs: union of every TOOL_HOME_DIRS, bare-relative --
# yolobox-init prefixes $HOME itself.
ALL_HOME_DIRS=()
homedirs_cb() {
    if [ -n "${TOOL_HOME_DIRS+x}" ]; then
        ALL_HOME_DIRS+=( "${TOOL_HOME_DIRS[@]}" )
    fi
}
yb_each_module homedirs_cb
printf '%s\n' "${ALL_HOME_DIRS[@]+"${ALL_HOME_DIRS[@]}"}" | sort -u > /opt/yolobox/manifest/home-dirs

# seed.sh: for each module defining tool_seed, emit `declare -f tool_seed`
# with the name rewritten to tool_seed_<module>, then a call line for that
# renamed function -- a bare concatenation of `declare -f` output would emit
# N *definitions* of the one name `tool_seed` and execute nothing.
# Verified on bash 3.2: rename via `sed '1s/^tool_seed/NAME/'`, append a call
# line for NAME, and the resulting file both defines and runs.
: > /opt/yolobox/manifest/seed.sh
seed_cb() {
    local m="$1" mod fn
    if declare -f tool_seed >/dev/null 2>&1; then
        mod="$(basename "${m}" .sh)"
        fn="tool_seed_$(printf '%s' "${mod}" | tr -c 'a-zA-Z0-9' '_')"
        {
            declare -f tool_seed | sed "1s/^tool_seed/${fn}/"
            printf '%s\n' "${fn}"
        } >> /opt/yolobox/manifest/seed.sh
    fi
}
yb_each_module seed_cb

echo "=== cleanup ==="
rm -rf /var/lib/apt/lists/*
chmod -R a+rX /usr/local /opt
# /usr/local ONLY. /opt stays root-owned — a box-user-owned /opt would let
# an agent `mv /opt/yolobox` aside and substitute the rendered MCP configs,
# since write permission on a PARENT allows rm/rename of its entries whatever
# their own mode. Every ad-hoc install path already targets /usr/local
# (NPM_CONFIG_PREFIX, CARGO_HOME, UV_INSTALL_DIR). NEVER chown /opt here.
chown -R "${UID_ARG}:${GID_ARG}" /usr/local

USERNAME_ARG="${USERNAME_ARG}" UID_ARG="${UID_ARG}" GID_ARG="${GID_ARG}" \
    "${here}/clean-home.sh"

echo "=== install-all.sh complete ==="
